### ISSUE TITLE
Naming convention config needed

### ISSUE THREAD

**Issue by such** [homebound-team/graphql-typescript-factories#13]
It appears that this namingConvention config is needed:

```
namingConvention:
        typeNames: keep
        enumValues: pascal-case#pascalCase
```

the default (`pascal-case#pascalCase`) breaks my Mutation payloads factories:
it creates:
```
export interface acceptOfferPayloadOptions {
  __typename?: "acceptOfferPayload";
  clientMutationId?: acceptOfferPayload["clientMutationId"];
  errors?: Array<UserErrorOptions>;
}
```

even though the type would actually be `AcceptOfferPayload`.

**Comment by stephenh** [comment]
This has been fixed in #45 . Sorry for not seeing this sooner, we've been missing the notifications on this repo for years :grimacing:
