### ISSUE TITLE
Usage with near-operation-file-preset?

### ISSUE THREAD

**Issue by leggomuhgreggo** [homebound-team/graphql-typescript-factories#33]
Hello! I was wondering if there's any way to use the plugin with [near-operation-file-preset plugin](https://www.graphql-code-generator.com/plugins/near-operation-file-preset), so that the factories are shaped/co-located with respect to individual .graphql documents.

Thanks!

**Comment by stephenh** [comment]
Hey @leggomuhgreggo ! Sorry for the late response here, we weren't getting notifications about Github issues :thinking: ...

Anyway, that's a great question, but no not really b/c the way our factories work today is that we make 1 factory per type in the schema, and not 1 factory per client query or client fragment.

I.e. if you do `query MyPageGetAuthors / authors { id name } `, the `newAuthor` factory that you'd use in the test isn't create specifically for the `MyPageGetAuthors` query/fragment, but it was created as soon as the `type Author` showed up in the the GraphQL schema.

Going to close this out, but happy to answer other questions.
