### ISSUE TITLE
There is an issue with the Yarn registry

### ISSUE THREAD

**Issue by soudanimarinho** [homebound-team/graphql-typescript-factories#59]
This is yarn registry UI when I try to [navigate to the package page](https://yarnpkg.com/package?q=graphql-typescript-factor&name=%40homebound%2Fgraphql-typescript-factories). This is an issue with the registry.

![image](https://github.com/homebound-team/graphql-typescript-factories/assets/130377135/7e8976bf-9f4f-4de3-ab15-a97d59e8de07)

**Comment by soudanimarinho** [comment]
@blimmer, this was caused by your last commit. Could you review it, please?

**Comment by blimmer** [comment]
As mentioned you your previous comments, acknowledged and working on a fix now.

**Comment by blimmer** [comment]
This is fixed. Sorry for the fire drill.
